### PR TITLE
Tidy and add download link for OsmAndMapCreator

### PR DESCRIPTION
**Pull request by JonnyTech**

### CODE REVIEW

**Comment by hvdwolf** [comment]
Thank you.

I haven't been privately in the UK for quite some time. Rental cars I use
for work come with builtin nav apps, so I had not looked at this repo for
quite some time.

Harry

Op zo 10 nov. 2019 om 20:54 schreef JonnyTech <notifications@github.com>:

**Comment by JonnyTech** [comment]
Thank you for merging. This project is very useful I have built the latest version today. Do you want a copy to host it here?

**Comment by hvdwolf** [comment]
Yes, please. I will of course give you the kudos for having built it.

Is JonnyTech how you would like to be referred to?

Harry

Op zo 10 nov. 2019 om 23:06 schreef JonnyTech <notifications@github.com>:

**Comment by JonnyTech** [comment]
No need for any kudos, I simply ran your script. How can I get it to you? It is 102Mb.

**Comment by hvdwolf** [comment]
I already created it myself, as it is indeed just running the script and
feed the osm.pbf to OsmandMapcreator.

Thanks.

Harry

Op zo 10 nov. 2019 om 23:23 schreef JonnyTech <notifications@github.com>:

**Pull request merged**
